apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - resource-limits.yaml
  - postgres.yaml
  - cms.yaml
  - frontend.yaml
  - network-policies.yaml
